# Generated by Django 2.2.4 on 2019-08-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dept',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
