# Generated by Django 2.2.4 on 2019-08-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customuser_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='userRole',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
