# Generated by Django 2.2.4 on 2019-08-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_customuser_userrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.CharField(max_length=20)),
                ('session', models.CharField(max_length=20)),
                ('dept', models.CharField(max_length=20)),
                ('batch', models.CharField(max_length=20)),
            ],
        ),
    ]
