# Generated by Django 2.2.4 on 2019-08-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_enrollcourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
